// <auto-generated />
using System;
using GestionCommerciale.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCommerciale.Shared.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911115738_AddReglementsGroupes")]
    partial class AddReglementsGroupes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GestionCommerciale.Modules.Achat.Models.BonAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonsAchat");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Achat.Models.BonAchatLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonAchatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonAchatId");

                    b.ToTable("BonAchatLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Achat.Models.PaiementBonAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonAchatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReglementGroupeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonAchatId");

                    b.HasIndex("ReglementGroupeId");

                    b.ToTable("PaiementsBonAchat");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.BonRetourFournisseur.Models.BonRetourFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonRetourId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonRetourId");

                    b.ToTable("BonsRetourFournisseurs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.BonRetourFournisseur.Models.BonRetourFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonRetourFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonRetourFournisseurId");

                    b.ToTable("BonRetourFournisseurLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Charges.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeChargeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("TypeChargeId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Charges.Models.TypeCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("TypesCharges");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.BonRetour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonsRetour");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.BonRetourLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonRetourId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonRetourId");

                    b.ToTable("BonRetourLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.ReglementGroupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiersId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TiersId");

                    b.HasIndex("TiersId", "Sens");

                    b.ToTable("ReglementsGroupes", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Sortie.Models.BonSortie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonsSortie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Sortie.Models.BonSortieLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonSortieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonSortieId");

                    b.ToTable("BonSortieLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Sortie.Models.PaiementBonSortie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonSortieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReglementGroupeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonSortieId");

                    b.HasIndex("ReglementGroupeId");

                    b.ToTable("PaiementsBonSortie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrigineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrigineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAvant")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<decimal>("PrixAchatHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixVenteHT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Tiers.Models.Tiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Officiel");

                    b.Property<string>("ConditionsPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tiers_Categorie", "Categorie IN ('Officiel', 'Comptoir')");
                        });
                });

            modelBuilder.Entity("GestionCommerciale.Shared.Database.AppSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupIntervalUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlocageSiStockInsuffisant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevisValiditeJoursDefaut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumberingFloorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableVirtualKeyboard")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteICE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteLogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteMentionsLegales")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteNom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TauxTVAJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Achat.Models.BonAchatLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Achat.Models.BonAchat", "BonAchat")
                        .WithMany("Lignes")
                        .HasForeignKey("BonAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonAchat");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Achat.Models.PaiementBonAchat", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Achat.Models.BonAchat", "BonAchat")
                        .WithMany("Paiements")
                        .HasForeignKey("BonAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonAchat");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.BonRetourFournisseur.Models.BonRetourFournisseur", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.BonRetour", "BonRetour")
                        .WithMany()
                        .HasForeignKey("BonRetourId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BonRetour");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.BonRetourFournisseur.Models.BonRetourFournisseurLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.BonRetourFournisseur.Models.BonRetourFournisseur", "BonRetourFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("BonRetourFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonRetourFournisseur");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Charges.Models.Charge", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Charges.Models.TypeCharge", "TypeCharge")
                        .WithMany()
                        .HasForeignKey("TypeChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeCharge");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.BonRetourLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.BonRetour", "BonRetour")
                        .WithMany("Lignes")
                        .HasForeignKey("BonRetourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonRetour");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Sortie.Models.BonSortieLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Sortie.Models.BonSortie", "BonSortie")
                        .WithMany("Lignes")
                        .HasForeignKey("BonSortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonSortie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Sortie.Models.PaiementBonSortie", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Sortie.Models.BonSortie", "BonSortie")
                        .WithMany("Paiements")
                        .HasForeignKey("BonSortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonSortie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.MouvementStock", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Stock.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Produit", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Stock.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Achat.Models.BonAchat", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.BonRetourFournisseur.Models.BonRetourFournisseur", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.BonRetour", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Sortie.Models.BonSortie", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
